name=ESP32S3CameraStream
version=1.0.0
author=Sajid Ahmed Rahi
maintainer=Sajid Ahmed Rahi <sajidahmedrahii@gmail.com>
sentence=ESP32 Camera streaming library for ESP32-S3-EYE
paragraph=Provides easy streaming and snapshot functionality for ESP32 camera modules
category=Communication
url=https://github.com/sajidrahii/ESP32S3_n8r16_CameraStream
architectures=esp32
depends=ESP32